// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica.Models;

#nullable disable

namespace PruebaTecnica.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnica.Models.Cliente", b =>
                {
                    b.Property<int>("idCLiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCLiente"));

                    b.Property<string>("nombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCLiente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PruebaTecnica.Models.Sorteo", b =>
                {
                    b.Property<int>("idSorteo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSorteo"));

                    b.Property<int>("numeroSorteo")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("idSorteo");

                    b.HasIndex("numeroSorteo")
                        .IsUnique();

                    b.ToTable("Sorteos");
                });

            modelBuilder.Entity("PruebaTecnica.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idSorteo")
                        .HasColumnType("int");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idUsuario");

                    b.HasIndex("idCliente");

                    b.HasIndex("idSorteo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PruebaTecnica.Models.Usuario", b =>
                {
                    b.HasOne("PruebaTecnica.Models.Cliente", "cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica.Models.Sorteo", "sorteo")
                        .WithMany("Usuarios")
                        .HasForeignKey("idSorteo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("sorteo");
                });

            modelBuilder.Entity("PruebaTecnica.Models.Cliente", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PruebaTecnica.Models.Sorteo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
